os:
    - linux
language: generic
sudo: required
dist: trusty

osx_image: xcode8.3
before_install:
     eval "$(curl -sL https://apt.vapor.sh)";
     sudo apt-get install vapor;
     sudo chmod -R a+rx /usr/;
 
script:
    - swift build -c release
    - swift test

after_success:
    - eval "$(curl -sL https://swift.vapor.sh/codecov)"
